quarkus:
  http:
    port: 8090
    grpc:
      server:
        port: 6566
  #quarkus.datasource.reactive.url=${HETZ_WELT_URL}
  datasource:
    reactive:
      url: postgresql://167.235.52.214/wiki1
    db-kind: postgresql
    username: dev
    password: ${HETZ_WELT_PASS}
  hibernate-orm:
    database:
      generation: update